### PR TITLE
Add ability to seal DNS servers

### PR DESCRIPTION
**Pull request by mor1**
A bit hacky perhaps, but seems to work.
Will see about tidying up use of IP addresses etc, but thought I'd open this for the time being to remind me and in case there's anything else that needs fixing :)

### CODE REVIEW

**Comment by hannesm** [comment]
I'm not sure about the scope of `mirage-seal`.  Given that `mirage-skeleton` has example unikernels (targeting unikernel developers in their early stage), should `mirage-seal` contain easily customisable unikernels (via command line arguments, targeting users (without interest in OCaml) with their own content)?  If so, I'd suggest to use a multi-argument binary (thus `seal http <options> <arguments>` and `seal dns <options> <arguments>` (maybe `seal https <options> <arguments>`?)).  The various commands can share their option and argument parsing code.

**Comment by mor1** [comment]
Hm-- that would make sense to me. This was just a quick hack to get something working :)  Is there a good example for a multi-argument binary using `cmdliner`?

To my mind, `mirage-skeleton` was always about heavily-documented sample code, while `mirage-seal` is a usable tool.

**Comment by samoht** [comment]
I think I'd prefer to keep the scope of `mirage-seal` focused around static websites. So maybe it's better to create an other tool to create safe/secure DNS server?

**Comment by mor1** [comment]
@samoht Well, it's your tool :) But isn't there at least some boilerplate shared between the two (or three) cases? But if you want seal to remain focused on HTTP/S then by all means close this one. (Otherwise let me know and I'll update it to latest Mirage.)

**Comment by samoht** [comment]
I am closing this PR, but the DNS boilerplate should go somewhere where people can use it :-) Maybe mirage-dns?

**Pull request closed without merging**
